services:
  oro_locale.entity_name_provider:
    class: Training\Bundle\UserNamingBundle\Provider\EntityNameProvider
    arguments:
      - '@oro_locale.formatter.name.link'
      - '@oro_locale.dql.formatter.name.link'
    tags:
      - { name: oro_entity.name_provider, priority: -80 }